### ISSUE TITLE
[BUG] No code in repo/Not hosted via GitHub Pages

### ISSUE THREAD

**Issue by KendallDoesCoding** [xchanmolx/portfolio#1]

**Comment by GustavoRidgue** [comment]
Hi @KendallDoesCoding !
There's no code in this repository, but the repository for this portifolio is https://github.com/xchanmolx/chantin-portfolio, and not this one

**Comment by KendallDoesCoding** [comment]
> Hi @KendallDoesCoding ! There's no code in this repository, but the repository for this portifolio is https://github.com/xchanmolx/chantin-portfolio, and not this one

Ok thanks, but then what is this repo used for?
